### ISSUE TITLE
Use of UCL account for github

### ISSUE THREAD

**Issue by PhilipDW183** [jreades/fsds#20]
Student lose access to their email once they graduate (potentially) so github should be set up with their personal email and then go through to add their UCL email separately to benefit from GitHub education benefits. Most will not make use of the github student benefits while they here anyway so having it on their personal account will probably be better to ensure that they still have access to it, even when they leave.

**Comment by jreades** [comment]
Resolved by updating GitHub page. See [commit 623a66f](https://github.com/jreades/sds_env/commit/623a66f273038f27cc44a401a08a844a9589b1d5).
