### ISSUE TITLE
Docker connection issue

### ISSUE THREAD

**Issue by PhilipDW183** [jreades/fsds#21]
Some students, if they do not open up the app, will not be able to used `docker` commands (either through the bash script or in their own terminal) until they open up the desktop app themselves. It could be added as an extra step just to see that docker runs on their laptop and removes a likely error.

**Comment by jreades** [comment]
Have added a note to this effect on the installation instructions. See commit [8b16a6dc](https://github.com/jreades/sds_env/commit/8b16a6dc35b28e01080d0d2f40d40cb7db16279d)
